#!/usr/bin/python


def motifFinder(string,sub,offset):
    '''Function to fing the index of the motifs'''
    indexList=[]
    i = string.find(sub,offset)
    while i >=0:
        indexList.append(i)
        i = string.find(sub,i+1)
    return indexList

if __name__=="__main__":
    string = "CCTATCATGTATCATGACTATCATGTATCATGTATCATGTATCATGATATATCATGCCACCGCACCCGTTGTATCATGAACCTTATGGTCTATCATGGGTTATCATGATATCATGTGTATATCATGTTATCATGAGTGATATCATGGCTGTATCATGCTATCATGATTATCATGTATCATGTATCATGTCTTATCATGGTATCATGTATCATGCGACTGATAACGAGGCTAGCGTATCATGATATATCATGTATCATGGTATCATGTATCATGTATCATGTAGAACTATCATGGTATCATGTTTTCTATCATGGATATCATGCTATCATGTAATATCATGCACTATCATGCTATCATGCTATCATGCATTCCGAATATCATGTATCATGGTATCATGTATCATGTATCATGTACCATAGTTATATCATGTATCATGGCGTTATCATGACTTATCATGGCTATCATGCCTATCATGTATCATGATATCATGTCTATCATGTTTATCATGTATCATGTACTAACTAGTATCATGCTAAGTTATCATGCACGTGGTTTATCATGCGTGTATCATGGACTATCATGGCTTTTTTGCTATCATGTGAGGAGGTATCATGAATTATCATGGCACGTCCAATATATCATGTATCATGAGCATATCATGTAGACTATCATGCTATCATGTATCATGTATCATGTTATCATGGTATCATGTATCATGCTATCATGATATCATGATCAGTTATATCATGATATTATCATGTATCATGTATCATGATATCATGTTATCATGTCATATCATGTATCATGTATCATGTATCATGTATCATGGGAGTATCATGATTATATCATGTATCATGTATCATGATATCATGCTCATATCATGTCTATCATGTTATATCATGAGGTTATCATGGTTGTTGTATCATGTATCATGTGCCGTATCATGGTATCATGTATCATGGGTATCATGATAA"
    sub   = "TATCATGTA"
    indexList = motifFinder(string,sub,offset=0)
    newList   = [1+i for i in indexList]
    print " ".join(map(str,newList))

